### ISSUE TITLE
Install & Setup

### ISSUE THREAD

**Issue by SvenMeyer** [RayHuang880301/gptutor-extension#1]
I am using VScode on Linux.

1) If I search for "GPTutor" or even just "GPT" (so it finds other extension), "GPTutor" does not show up in the list of available extension in the marketplace.

![image](https://user-images.githubusercontent.com/25609/236188516-9ea830db-65fd-4b02-a301-0c19d220ed79.png)

Thus I downloaded the extension `gptutor.gptutor-0.0.5.vsix` and installed that.
https://marketplace.visualstudio.com/items?itemName=gptutor.gptutor

2) Now GPTutor shows up in the list of installed extensions, but `init` command does not work and strangely GPTutor does not show up in User or Workspace settings ...

![VScode - Extensions - GPTutor](https://user-images.githubusercontent.com/25609/236188202-c527cba2-9377-4989-8b58-d426e18c0da9.png)

Eventually after restarting code 3x and trying it 2-3 more times, I managed to set the API key and model ...

3) When I execute GPTutor:Active or GPTutor:Audit I get just a white input fiel in the top left (see 4) and an error message ...

![image](https://user-images.githubusercontent.com/25609/236191602-0eb15d22-ad3d-4f0d-8340-d9a74d5f4db1.png)

4) Here it looks like GPTutor is currently the active Extension which is a bit hard to figure out because there is no icon, just a black area ..

5) When I type a question into th einput field and hit Return, nothing comes back ...

![image](https://user-images.githubusercontent.com/25609/236191031-7981866a-f712-4f97-b004-2f26766df61f.png)

**Comment by EasonC13** [comment]
We are delighted to inform you that GPTutor has undergone an update, resulting in a new onboarding flow. We are confident that this update has addressed the issue you raised.
